### ISSUE TITLE
Automatic turn sound on even if it was off before monitor standby

### ISSUE THREAD

**Issue by Peppins32** [fxsound2/fxsound-app#436]
**Describe the bug**
If i disable sound (from taskbar) and my monitor go in standby, when i move mouse to use pc again, the sound is turned on, but i leaved it off.

This happen even if i set FXsound enabled or disabled, you just need to have it running in background, and also if i set internal soundcard as default instead of hdmi.

**To Reproduce**
1. Turn sound off
2. Let monitor go in standby
3. Move the mouse to turn it on (monitor)
4. When you're back in windows, the sound is on again

**Expected behavior**
The sound need to stay off

**System information**
 - Windows 11
 - HDMI/Internal sound card
 - FxSound 1.2.3.0

**Comment by Peppins32** [comment]
It doesn't happen to me. If I set HDMI as the only audio output, when it goes into standby and was muted, when it turns back on it remains muted. Having started fxsound this doesn't happen, fxsound enables the audio again (even if i have forced hdmi output here too and/or disabled fxsound).

**Comment by Peppins32** [comment]
Updated to new 1.2.4.0 version but the problem is still here.

**Comment by bvijay74** [comment]
FxSound enabling sound (unmuting) automatically is fixed in v1.2.10.0

**Comment by Peppins32** [comment]
I updated fxsound but unfortunately it still doesn't work, in fact I can say that now it's worse than before, in the sense that it tends to freeze after the monitor goes into standby if I try to change devices. I should add that it also changes devices even though I have set the monitor as the default, it still reactivates the audio (the icon in the bottom right is no longer deactivated and even deactivating and reactivating it doesn't change anything, after the monitor is turned back on, I mean). The audio doesn't work when the monitor is reactivated even though it appears to be active (but deactivated before standby), and it tends to freeze when changing manually. I tested this with VLC playing with a song, then muting the audio in the bottom right but still leaving VLC playing, the monitor then goes into standby and when I restart the monitor, i don't listen the sound, the icon in the bottom right is no longer deactivated but you can't hear anything, deactivating it again and reactivating it doesn't change, it still isn't heard. If fxsound has changed devices and I try to force it on the monitor, everything freezes and if/when it works, the audio still goes missing, I have to restart VLC. This doesn't happen IF you only use Windows and don't use fxsound.

EDIT. i've disabed the integrated soundcard, so now only with monitor, it work like before: sound disabled, monitor go into standby, resume from the standby and sound is on again. The freeze etc was about auto switch of sound output of fxsound for no reason, with only the monitor there isn't this issue btw.
